FROM rust:1.65

ENV LOG_LEVEL debug

RUN apt update && \
    apt install \
    gcc 
#musl-dev musl-tools

RUN cargo install cargo-watch

WORKDIR /notify-server
COPY . .

CMD ["cargo", "watch", "-x", "run"]