edition = "2021"

reorder_imports = true
use_try_shorthand = true
remove_nested_parens = true
reorder_modules = true
use_field_init_shorthand = true

## We only use settings available in the stable channel

#fn_single_line = false
#format_code_in_doc_comments = true
#format_strings = true
#imports_layout = "HorizontalVertical"
#imports_granularity = "One"
#normalize_comments = true
#normalize_doc_attributes = true
#reorder_impl_items = true
#group_imports = "StdExternalCrate"
#wrap_comments = true
#overflow_delimited_expr = true
#unstable_features = true
