name: ⚙️ Deploy to Dev
run-name: "Deploy to Dev: ${{ github.sha }} ➠ ${{ (!inputs.deploy-infra && !inputs.deploy-app) && ' 👀 deploy nothing' || ''}}${{ inputs.deploy-infra && ' ❱❱  infra' || '' }}${{ inputs.deploy-app && ' ❱❱  app' || '' }}"

on:
  push:
    branches:
      - "178-chore-enable-deployments-to-dev-account"
  workflow_dispatch:
    inputs:
      deploy-infra:
        description: "Deploy Infra"
        default: true
        required: true
        type: boolean
      deploy-app:
        description: "Deploy App"
        default: true
        required: true
        type: boolean

concurrency: deploy

permissions:
  contents: write
  checks: write
  id-token: write
  packages: write


jobs:
  ci:
    name: CI
    uses: WalletConnect/ci_workflows/.github/workflows/sub-ci.yml@1.0.0
    secrets: inherit
    with:
      check-infra: true
      check-app: true


#  cd:
#    name: CD
#    uses: ./.github/workflows/sub-cd.yml
#    secrets: inherit
#    with:
#      deploy-infra: ${{ inputs.deploy-infra }}
#      deploy-app: ${{ inputs.deploy-app }}
#      deploy-prod: ${{ inputs.stage == 'prod' }}
#      version: ${{ inputs.version }}
