name: ❖ Validate Rust

on:
  workflow_call:
    inputs:
      stage:
        description: 'the environment to validate'
        required: true
        type: string
      stage-url:
        description: 'the URL of the environment'
        required: true
        type: string

permissions:
  contents: read
  checks: write
  id-token: write

jobs:
  health-check:
    name: Health Check - ${{ inputs.stage }}
    runs-on:
      group: ${{ vars.RUN_GROUP }}
    environment:
      name: ${{ inputs.stage }}
      url: ${{ inputs.stage-url }}
    steps:
      - name: health-check
        run: curl "${{ inputs.stage-url }}"
