name: ❖ App - Deploy

on:
  workflow_call:
    inputs:
      version:
        description: 'the release version'
        type: string
        required: true
      stage:
        description: 'the environment to deploy to'
        type: string
        default: 'staging'
      stage-url:
        description: 'the URL of the environment'
        type: string
        default: https://${{ vars.SUBDOMAIN_NAME }}.walletconnect.com/health
      aws-role-arn:
        description: 'the ARN of the AWS role to assume'
        type: string
        default: https://${{ vars.SUBDOMAIN_NAME }}.walletconnect.com/health

permissions:
  contents: read
  id-token: write

jobs:
  deploy-app:
    name: Deploy App `${{ inputs.stage }}`
    runs-on:
      group: ${{ vars.RUN_GROUP }}
    environment:
      name: ${{ inputs.stage }}
      url: ${{ inputs.environment_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ inputs.aws-role-arn }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to ECR repository
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Deploy image to ECS
        id: deploy
        uses: WalletConnect/actions/aws/ecs/deploy-image/@2.1.4
        with:
          aws-role-arn: ${{ inputs.aws-role-arn }}
          aws-region: ${{ vars.AWS_REGION }}
          cluster-name: wc-${{ vars.AWS_REGION }}-${{ inputs.stage }}-${{ vars.IMAGE_NAME }}-cluster
          service-name: wc-${{ vars.AWS_REGION }}-${{ inputs.stage }}-${{ vars.IMAGE_NAME }}-service
          task-definition-name: wc-${{ vars.AWS_REGION }}-${{ inputs.stage }}-${{ vars.IMAGE_NAME }}
          image-name: ${{ steps.login-ecr.outputs.registry }}/${{ vars.IMAGE_NAME }}:${{ inputs.version }}
