
name: Validate with Swift

on:
  workflow_call:
    inputs:
      relay-endpoint:
        description: 'The endpoint of the relay e.g. relay.walletconnect.com'
        required: true
        type: string
      notify-endpoint:
        description: 'The endpoint of the notify server e.g. notify.walletconnect.com'
        required: true
        type: string
      swiftBranch:
        description: 'Swift branch to run on'
        required: false
        default: 'main'
        type: string
    secrets:
      project_id:
        description: "The project ID to use to use as for the Swift client"
        required: true
      dapp_project_id:
        description: "The project ID to use as the test dapp"
        required: true
      dapp_project_secret:
        description: "The project secret to use for the test dapp"
        required: true

jobs:
  notify_tests:
    permissions:
      contents: write
    runs-on:
      group: apple-silicon
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: WalletConnect/WalletConnectSwiftV2
        ref: ${{ github.event.inputs.swiftBranch }}

    - name: Run Notify Tests
      uses: ./.github/actions/run_tests_without_building
      with:
        type: 'notify-tests'
        relay-endpoint: ${{ github.event.inputs.relay-endpoint }}
        notify-endpoint: ${{ github.event.inputs.notify-endpoint }}
        project-id: ${{ secrets.project_id }}
        gm-dapp-project-id: ${{ secrets.dapp_project_id }}
        gm-dapp-project-secret: ${{ secrets.dapp_project_secret }}
