
name: Validate with Swift

on:
  workflow_dispatch:
    inputs:
      relay-endpoint:
        description: 'The endpoint of the relay e.g. relay.walletconnect.com'
        required: false
        default: 'staging.relay.walletconnect.com'
        type: string
      notify-endpoint:
        description: 'The endpoint of the notify server e.g. notify.walletconnect.com'
        required: false
        default: 'staging.notify.walletconnect.com'
        type: string
      swiftBranch:
        description: 'Swift branch to run on'
        required: false
        default: 'main'
        type: string
  workflow_call: 
    inputs: 
      relay-endpoint: 
        description: 'The endpoint of the relay e.g. relay.walletconnect.com'
        required: true
        type: string
      notify-endpoint:
        description: 'The endpoint of the notify server e.g. notify.walletconnect.com'
        required: true
        type: string
      swiftBranch:
        description: 'Swift branch to run on'
        required: false
        default: 'main'
        type: string

jobs:
  notify_tests:
    permissions: 
      contents: write
    runs-on:
      group: apple-silicon
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: WalletConnect/WalletConnectSwiftV2
        ref: ${{ github.event.inputs.swiftBranch }}

    - name: Run Notify Tests
      uses: ./.github/actions/run_tests_without_building
      with:
        type: 'notify-tests'
        relay-endpoint: ${{ github.event.inputs.relay-endpoint }}
        project-id: ${{ secrets.PROJECT_ID }}
        notify-endpoint: ${{ github.event.inputs.notify-endpoint }}
        gm-dapp-project-id: ${{ secrets.GM_DAPP_PROJECT_ID }}
        gm-dapp-project-secret: ${{ secrets.GM_DAPP_PROJECT_SECRET }} 
